name: CI

on:
  push:
    branches:
      - '**'

jobs:

  check:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Check
        run: make check

      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.41.1
          skip-pkg-cache: true
          skip-build-cache: true

      - name: Test
        run: make test

      - name: Acceptance Test
        run: make testacc
        env:
          RANDOM_ENV: ${{ env.TESTS.RANDOM_ENV }}
