name: CI

on:
  push:
    branches:
      - '**'

jobs:

  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

#      - name: Set up Go
#        uses: actions/setup-go@v2
#        with:
#          go-version: 1.16

      - name: Manual go setup
        run: |
          pwd
          curl https://dl.google.com/go/go1.16.6.linux-amd64.tar.gz -o go1.16.6.linux-amd64.tar.gz
          rm -rf _go_
          mkdir _go_
          tar -C _go_ -xzf go1.16.6.linux-amd64.tar.gz
          export PATH=$PATH:$(pwd)/_go_
          go version

      - name: Check
        run: make check

      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.41.1
          skip-pkg-cache: true
          skip-build-cache: true

      - name: Test
        run: make test

  acceptance:
    name: Acceptance test
    environment: TESTS
    runs-on: self-hosted
    needs: check
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Acceptance Test3
        run: make testacc
        env:
          RANDOM_ENV: ${{ secrets.THE_VAL }}
