name: CI

on:
  push:
    branches:
      - '**'

concurrency: acceptance_test

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Check
        run: make check

      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.41.1
          skip-pkg-cache: true
          skip-build-cache: true

      - name: Test
        run: make test

  acceptance:
    name: Acceptance test
    environment: TESTS
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Set up env
        env:
          RANDOM_ENV: ${{ secrets.THE_VAL }}
        run: |
          echo "RANDOM_ENV = $RANDOM_ENV"
          echo $RANDOM_ENV > env-file.sh
          export

      - name: Print env
        run: |
          ls -la
          echo $RANDOM_ENV
          export
          cat env-file.sh

      - name: Acceptance Test3
        run: make testacc
        env:
          RANDOM_ENV: ${{ secrets.THE_VAL }}
